package app.view;

import app.controller.PrincipalController;

/**
 *
 * @author Daniel Sánchez S.
 * @version 2.0
 */
public class ChatView extends javax.swing.JPanel {

    /**
     * Creates new form ChatView
     */
    public ChatView() {
        initComponents();
    }

    public ChatView(String id, PrincipalController principalController) throws Exception {
        initComponents();
        this.principalController = principalController;
        contactIdLabel.setText(id);
        timeLastTimeLabel.setText(principalController.getLasTime(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contactIdLabel = new javax.swing.JLabel();
        lastTimeLabel = new javax.swing.JLabel();
        timeLastTimeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();
        sendMessageButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        contactIdLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contactIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactIdLabel.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(16, 8, 16, 8);
        add(contactIdLabel, gridBagConstraints);

        lastTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lastTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastTimeLabel.setText("Last time: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(lastTimeLabel, gridBagConstraints);

        timeLastTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timeLastTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLastTimeLabel.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(timeLastTimeLabel, gridBagConstraints);

        messagesTextArea.setEditable(false);
        messagesTextArea.setColumns(20);
        messagesTextArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        messagesTextArea.setForeground(new java.awt.Color(56, 188, 255));
        messagesTextArea.setRows(5);
        jScrollPane1.setViewportView(messagesTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jScrollPane1, gridBagConstraints);

        sendMessageButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendMessageButton.setForeground(new java.awt.Color(255, 255, 255));
        sendMessageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-forward-arrow-45.png"))); // NOI18N
        sendMessageButton.setActionCommand("Send");
        sendMessageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendMessageButton.setPreferredSize(new java.awt.Dimension(85, 41));
        sendMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sendMessageButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(sendMessageButton, gridBagConstraints);

        messageTextArea.setColumns(20);
        messageTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageTextArea.setForeground(new java.awt.Color(255, 255, 255));
        messageTextArea.setRows(5);
        jScrollPane2.setViewportView(messageTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void sendMessageButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageButtonMouseReleased
        if (!"".equals(messageTextArea.getText())) {
            principalController.sendMessage();
        }
    }//GEN-LAST:event_sendMessageButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel contactIdLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastTimeLabel;
    public javax.swing.JTextArea messageTextArea;
    public javax.swing.JTextArea messagesTextArea;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JLabel timeLastTimeLabel;
    // End of variables declaration//GEN-END:variables
    
    PrincipalController principalController;
}
