package app.view;

import app.controller.LoginController;
import app.model.LoginModel;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;

/**
 *
 * @author Daniel Sánchez S.
 * @version 2.0
 */
public class LoginView extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        model = new LoginModel();
        controller = new LoginController(model, this);
        initView();
    }

    public void setController(LoginController controller) {
        this.controller = controller;
    }

    public LoginModel getModel() {
        return model;
    }

    public void setModel(LoginModel model) {
        this.model = model;
        model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(110, 0), new java.awt.Dimension(100, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(110, 0), new java.awt.Dimension(100, 32767));
        dogIconLabel = new javax.swing.JLabel();
        bodyLogInPanel = new javax.swing.JPanel();
        MessageLabel = new javax.swing.JLabel();
        topBarPanel = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1, 10), new java.awt.Dimension(32767, 0));
        minimizeButton = new javax.swing.JButton();
        maximizeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setPreferredSize(new java.awt.Dimension(800, 590));
        mainPanel.setLayout(new java.awt.BorderLayout());

        bodyPanel.setBackground(new java.awt.Color(44, 62, 75));
        bodyPanel.setPreferredSize(new java.awt.Dimension(800, 590));
        bodyPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        bodyPanel.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        bodyPanel.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        bodyPanel.add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        bodyPanel.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        bodyPanel.add(filler5, gridBagConstraints);

        dogIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-dog-100.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        bodyPanel.add(dogIconLabel, gridBagConstraints);

        bodyLogInPanel.setBackground(new java.awt.Color(143, 182, 208));
        bodyLogInPanel.setPreferredSize(new java.awt.Dimension(325, 400));
        bodyLogInPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        bodyPanel.add(bodyLogInPanel, gridBagConstraints);

        MessageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MessageLabel.setText("Error: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        bodyPanel.add(MessageLabel, gridBagConstraints);

        mainPanel.add(bodyPanel, java.awt.BorderLayout.CENTER);

        topBarPanel.setBackground(new java.awt.Color(35, 50, 60));
        topBarPanel.setForeground(new java.awt.Color(44, 62, 75));
        topBarPanel.setPreferredSize(new java.awt.Dimension(1280, 35));
        topBarPanel.setLayout(new javax.swing.BoxLayout(topBarPanel, javax.swing.BoxLayout.LINE_AXIS));
        topBarPanel.add(filler7);

        minimizeButton.setForeground(new java.awt.Color(41, 43, 46));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-minimize-window-35.png"))); // NOI18N
        minimizeButton.setToolTipText("");
        minimizeButton.setBorder(null);
        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        topBarPanel.add(minimizeButton);

        maximizeButton.setForeground(new java.awt.Color(41, 43, 46));
        maximizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-maximize-window-35.png"))); // NOI18N
        maximizeButton.setToolTipText("");
        maximizeButton.setBorder(null);
        maximizeButton.setBorderPainted(false);
        maximizeButton.setContentAreaFilled(false);
        maximizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maximizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeButtonMouseClicked(evt);
            }
        });
        topBarPanel.add(maximizeButton);

        closeButton.setForeground(new java.awt.Color(41, 43, 46));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-delete-35.png"))); // NOI18N
        closeButton.setToolTipText("");
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        topBarPanel.add(closeButton);

        mainPanel.add(topBarPanel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void maximizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeButtonMouseClicked
        if (getExtendedState() == JFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(JFrame.NORMAL);
        } else {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_maximizeButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void initView() {
        MessageLabel.setVisible(false);
        controller.setSignIn(new SignInView());
        controller.setSignUp(new SignUpView());
        bodyLogInPanel.add(controller.getSignIn());
        this.validate();
        this.repaint();
        controller.setCurrentPanel(controller.getSignIn());
    }

    public void closeFrame() {
        System.exit(0);
    }

    @Override
    public void update(Observable o, Object arg) {
        validate();
        repaint();
    }

    private LoginController controller;
    private LoginModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel MessageLabel;
    public javax.swing.JPanel bodyLogInPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dogIconLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton maximizeButton;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
