package app.view;

import app.gui.prefabs.ChatContainer;
import app.controller.PrincipalController;
import app.controller.RightBarController;
import app.model.PrincipalModel;
import app.services.Proxy;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;

/**
 *
 * @author Daniel Sánchez S.
 * @version 2.0
 */
public class PrincipalView extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    private void initView() {
        rightSideBarPanel.add(rightBarController.getView());
        Proxy.setRightController(rightBarController);
        rightBarController.settingAllId();
        this.validate();
        this.repaint();
    }

    public void setController(PrincipalController controller) {
        this.controller = controller;
    }

    public void setrightController(RightBarController rightBarController) {
        this.rightBarController = rightBarController;
        rightBarController.setPrincipalModel(controller);
        initView();
    }

    public PrincipalModel getModel() {
        return model;
    }

    public void setModel(PrincipalModel model) {
        this.model = model;
        rightBarController.getModel().setPrincipalmodel(model);
        model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatsPanel = new javax.swing.JPanel();
        leftSideBarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 16));
        LeftBarMessagerPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        rightSideBarPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(25, 32767));
        optionsButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1, 10), new java.awt.Dimension(32767, 0));
        minimizeButton = new javax.swing.JButton();
        maximizeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        bodyPanel.setBackground(new java.awt.Color(77, 119, 135));
        bodyPanel.setForeground(new java.awt.Color(153, 153, 153));
        bodyPanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                bodyPanelAncestorResized(evt);
            }
        });
        bodyPanel.setLayout(new java.awt.BorderLayout());

        chatsPanel.setBackground(new java.awt.Color(77, 119, 135));
        jScrollPane1.setViewportView(chatsPanel);

        bodyPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainPanel.add(bodyPanel, java.awt.BorderLayout.CENTER);

        leftSideBarPanel.setBackground(new java.awt.Color(41, 43, 46));
        leftSideBarPanel.setPreferredSize(new java.awt.Dimension(250, 250));
        leftSideBarPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-dog-paw-print-50.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        leftSideBarPanel.add(jLabel1, gridBagConstraints);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        leftSideBarPanel.add(nameLabel, gridBagConstraints);
        leftSideBarPanel.add(filler5, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        leftSideBarPanel.add(LeftBarMessagerPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        leftSideBarPanel.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        leftSideBarPanel.add(filler4, gridBagConstraints);

        mainPanel.add(leftSideBarPanel, java.awt.BorderLayout.WEST);

        rightSideBarPanel.setBackground(new java.awt.Color(41, 43, 46));
        rightSideBarPanel.setPreferredSize(new java.awt.Dimension(250, 250));
        rightSideBarPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(rightSideBarPanel, java.awt.BorderLayout.EAST);

        topBarPanel.setBackground(new java.awt.Color(25, 27, 29));
        topBarPanel.setForeground(new java.awt.Color(41, 43, 46));
        topBarPanel.setPreferredSize(new java.awt.Dimension(1280, 35));
        topBarPanel.setLayout(new javax.swing.BoxLayout(topBarPanel, javax.swing.BoxLayout.LINE_AXIS));
        topBarPanel.add(filler2);

        optionsButton.setBackground(getBackground());
        optionsButton.setForeground(new java.awt.Color(41, 43, 46));
        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-more-35.png"))); // NOI18N
        optionsButton.setToolTipText("");
        optionsButton.setBorder(null);
        optionsButton.setBorderPainted(false);
        optionsButton.setContentAreaFilled(false);
        optionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });
        topBarPanel.add(optionsButton);
        topBarPanel.add(filler1);

        minimizeButton.setBackground(getBackground());
        minimizeButton.setForeground(new java.awt.Color(41, 43, 46));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-minimize-window-35.png"))); // NOI18N
        minimizeButton.setToolTipText("");
        minimizeButton.setBorder(null);
        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        topBarPanel.add(minimizeButton);

        maximizeButton.setBackground(getBackground());
        maximizeButton.setForeground(new java.awt.Color(41, 43, 46));
        maximizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-maximize-window-35.png"))); // NOI18N
        maximizeButton.setToolTipText("");
        maximizeButton.setBorder(null);
        maximizeButton.setBorderPainted(false);
        maximizeButton.setContentAreaFilled(false);
        maximizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maximizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeButtonMouseClicked(evt);
            }
        });
        maximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximizeButtonActionPerformed(evt);
            }
        });
        topBarPanel.add(maximizeButton);

        closeButton.setBackground(getBackground());
        closeButton.setForeground(new java.awt.Color(41, 43, 46));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-delete-35.png"))); // NOI18N
        closeButton.setToolTipText("");
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        topBarPanel.add(closeButton);

        mainPanel.add(topBarPanel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        controller.signOut();
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void maximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maximizeButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void maximizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeButtonMouseClicked
        if (getExtendedState() == JFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(JFrame.NORMAL);
        } else {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_maximizeButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void bodyPanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_bodyPanelAncestorResized
        if (model != null) {
            model.commit();
        }
    }//GEN-LAST:event_bodyPanelAncestorResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (this.getSize().width <= 1000)
            rightSideBarPanel.setVisible(false);
        else
            rightSideBarPanel.setVisible(true);
    }//GEN-LAST:event_formComponentResized

    @Override
    public void update(Observable o, Object arg) {
        chatsPanel.removeAll();
        chatsPanel.setPreferredSize(new Dimension(bodyPanel.getSize().width, rightBarController.getModel().getUsuarios().size() * ChatContainer.DEFAULT_HEIGHT + (rightBarController.getModel().getUsuarios().size() * 7) + 7));
        LeftBarMessagerPanel.removeAll();
        LeftBarMessagerPanel.setPreferredSize(new Dimension(leftSideBarPanel.getSize().width, rightBarController.getModel().getUsuarios().size() * ChatContainer.DEFAULT_HEIGHT + (rightBarController.getModel().getUsuarios().size() * 3) + 3));
        for (String it : rightBarController.getModel().getUsuarios()) {
            ChatContainer ccPrincipal = new ChatContainer(it);
            ccPrincipal.setBackground(new Color(47, 49, 54));
            ccPrincipal.setPrincipalController(controller);
            chatsPanel.add(ccPrincipal);
            ChatContainer ccLeft = new ChatContainer(it);
            ccLeft.setBackground(new Color(47, 49, 54));
            ccLeft.setPrincipalController(controller);
            LeftBarMessagerPanel.add(ccLeft);
        }
        validate();
        repaint();
    }

    PrincipalController controller;
    PrincipalModel model;
    RightBarController rightBarController = new RightBarController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftBarMessagerPanel;
    public javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel chatsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftSideBarPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton maximizeButton;
    private javax.swing.JButton minimizeButton;
    public javax.swing.JLabel nameLabel;
    private javax.swing.JButton optionsButton;
    private javax.swing.JPanel rightSideBarPanel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables

}
