package app.view;

import app.controller.RightBarController;
import app.model.RightBarModel;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Daniel Sánchez S.
 * @version 2.0
 */
public class RightBarView extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form RightPrincipalPanel
     */
    public RightBarView() {
        initComponents();
    }
        
    public void setController(RightBarController controller) {
        this.controller = controller;
    }

    public RightBarModel getModel() {
        return model;
    }

    public void setModel(RightBarModel model) {
        this.model = model;
        model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rightSideBarPanel = new javax.swing.JPanel();
        heightfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        signOuttButton = new javax.swing.JButton();
        rightfiller = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        inMiddlefiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        downfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        newMessageButton = new javax.swing.JButton();
        leftfiller = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        upfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 16));
        searchContactButton = new javax.swing.JButton();
        searchContactTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contactsComboBox = new javax.swing.JComboBox<>();
        sepCombofiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 16));

        setLayout(new java.awt.BorderLayout());

        rightSideBarPanel.setBackground(new java.awt.Color(41, 43, 46));
        rightSideBarPanel.setPreferredSize(new java.awt.Dimension(250, 250));
        rightSideBarPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weighty = 0.1;
        rightSideBarPanel.add(heightfiller, gridBagConstraints);

        signOuttButton.setForeground(new java.awt.Color(41, 43, 46));
        signOuttButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-exit-50.png"))); // NOI18N
        signOuttButton.setToolTipText("");
        signOuttButton.setBorder(null);
        signOuttButton.setBorderPainted(false);
        signOuttButton.setContentAreaFilled(false);
        signOuttButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOuttButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-exit-45.png"))); // NOI18N
        signOuttButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signOuttButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        rightSideBarPanel.add(signOuttButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 6;
        rightSideBarPanel.add(rightfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.1;
        rightSideBarPanel.add(inMiddlefiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        rightSideBarPanel.add(downfiller, gridBagConstraints);

        newMessageButton.setForeground(new java.awt.Color(41, 43, 46));
        newMessageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-new-message-50.png"))); // NOI18N
        newMessageButton.setToolTipText("");
        newMessageButton.setBorder(null);
        newMessageButton.setBorderPainted(false);
        newMessageButton.setContentAreaFilled(false);
        newMessageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newMessageButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-new-message-45.png"))); // NOI18N
        newMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newMessageButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        rightSideBarPanel.add(newMessageButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 6;
        rightSideBarPanel.add(leftfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        rightSideBarPanel.add(upfiller, gridBagConstraints);

        searchContactButton.setForeground(new java.awt.Color(41, 43, 46));
        searchContactButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-search-35.png"))); // NOI18N
        searchContactButton.setToolTipText("");
        searchContactButton.setBorder(null);
        searchContactButton.setBorderPainted(false);
        searchContactButton.setContentAreaFilled(false);
        searchContactButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        rightSideBarPanel.add(searchContactButton, gridBagConstraints);

        searchContactTextField.setBackground(new java.awt.Color(41, 43, 46));
        searchContactTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchContactTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchContactTextField.setText("  search contact");
        searchContactTextField.setBorder(null);
        searchContactTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchContactTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        searchContactTextField.setPreferredSize(new java.awt.Dimension(100, 16));
        searchContactTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchContactTextFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchContactTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchContactTextFieldMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        rightSideBarPanel.add(searchContactTextField, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(40, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        rightSideBarPanel.add(jSeparator1, gridBagConstraints);

        contactsComboBox.setBackground(new java.awt.Color(41, 43, 46));
        contactsComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contactsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        contactsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--No selected--" }));
        contactsComboBox.setBorder(null);
        contactsComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        rightSideBarPanel.add(contactsComboBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        rightSideBarPanel.add(sepCombofiller, gridBagConstraints);

        add(rightSideBarPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void newMessageButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMessageButtonMouseReleased
        if(contactsComboBox.getSelectedItem() != "--No selected--"){
            controller.addMessagePanel((String) contactsComboBox.getSelectedItem());
        }else{
            //no contact selected
        }
    }//GEN-LAST:event_newMessageButtonMouseReleased

    private void searchContactTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchContactTextFieldMouseClicked
        searchContactTextField.setText("");
    }//GEN-LAST:event_searchContactTextFieldMouseClicked

    private void searchContactTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchContactTextFieldMouseEntered
        searchContactTextField.setBackground(Color.GRAY);
    }//GEN-LAST:event_searchContactTextFieldMouseEntered

    private void searchContactTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchContactTextFieldMouseExited
        searchContactTextField.setBackground(new Color(41, 43, 46));
    }//GEN-LAST:event_searchContactTextFieldMouseExited

    private void signOuttButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOuttButtonMouseReleased
        controller.getPrincipalController().signOut();
    }//GEN-LAST:event_signOuttButtonMouseReleased

    
    @Override
    public void update(Observable o, Object arg) {
        controller.fillAllId();
    }
    
    RightBarController controller;
    RightBarModel model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> contactsComboBox;
    private javax.swing.Box.Filler downfiller;
    private javax.swing.Box.Filler heightfiller;
    private javax.swing.Box.Filler inMiddlefiller;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.Box.Filler leftfiller;
    private javax.swing.JButton newMessageButton;
    private javax.swing.JPanel rightSideBarPanel;
    private javax.swing.Box.Filler rightfiller;
    private javax.swing.JButton searchContactButton;
    private javax.swing.JTextField searchContactTextField;
    private javax.swing.Box.Filler sepCombofiller;
    private javax.swing.JButton signOuttButton;
    private javax.swing.Box.Filler upfiller;
    // End of variables declaration//GEN-END:variables

}
