package app.view;

import app.controller.LoginController;
import app.model.LoginModel;
import java.awt.Color;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Daniel Sánchez S.
 * @version 2.0
 */
public class SignUpView extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form SingUpView
     */
    public SignUpView() {
        initComponents();
        this.setVisible(true);
    }

    public void setController(LoginController controller) {
        this.controller = controller;
    }

    public LoginModel getModel() {
        return model;
    }

    public void setModel(LoginModel model) {
        this.model = model;
        model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        signUpPanel = new javax.swing.JPanel();
        userIconLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        idIconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        passwordLabel = new javax.swing.JLabel();
        passwordIconLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        upfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        downfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 32));
        iconfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        leftIconfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        rightIconfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        nameLabel = new javax.swing.JLabel();
        nameIconLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        signUpBtnPanel = new javax.swing.JPanel();
        singUpLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(325, 400));
        setLayout(new java.awt.BorderLayout());

        signUpPanel.setBackground(new java.awt.Color(143, 182, 208));
        signUpPanel.setPreferredSize(new java.awt.Dimension(325, 400));
        signUpPanel.setLayout(new java.awt.GridBagLayout());

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-user-60.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 44);
        signUpPanel.add(userIconLabel, gridBagConstraints);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("User:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(userLabel, gridBagConstraints);

        idIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-user-24.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(idIconLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");
        jSeparator1.setMinimumSize(new java.awt.Dimension(15, 5));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(15, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(jSeparator1, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(passwordLabel, gridBagConstraints);

        passwordIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-privacy-24.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(passwordIconLabel, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setToolTipText("");
        jSeparator2.setMinimumSize(new java.awt.Dimension(15, 5));
        jSeparator2.setOpaque(true);
        jSeparator2.setPreferredSize(new java.awt.Dimension(15, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(jSeparator2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        signUpPanel.add(upfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        signUpPanel.add(downfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        signUpPanel.add(iconfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        signUpPanel.add(leftIconfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        signUpPanel.add(rightIconfiller, gridBagConstraints);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(nameLabel, gridBagConstraints);

        nameIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-contact-details-24.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(nameIconLabel, gridBagConstraints);

        nameTextField.setBackground(new java.awt.Color(143, 182, 208));
        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(255, 255, 255));
        nameTextField.setText("Name");
        nameTextField.setBorder(null);
        nameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        nameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nameTextField.setMinimumSize(new java.awt.Dimension(100, 24));
        nameTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        signUpPanel.add(nameTextField, gridBagConstraints);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setToolTipText("");
        jSeparator3.setMinimumSize(new java.awt.Dimension(15, 5));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(15, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signUpPanel.add(jSeparator3, gridBagConstraints);

        signUpBtnPanel.setBackground(new java.awt.Color(143, 182, 208));
        signUpBtnPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        signUpBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtnPanel.setPreferredSize(new java.awt.Dimension(72, 32));
        signUpBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpBtnPanelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signUpBtnPanelMouseReleased(evt);
            }
        });

        singUpLabel.setBackground(new java.awt.Color(255, 255, 255));
        singUpLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        singUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        singUpLabel.setText("Sign Up");
        signUpBtnPanel.add(singUpLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        signUpPanel.add(signUpBtnPanel, gridBagConstraints);

        idTextField.setBackground(new java.awt.Color(143, 182, 208));
        idTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setText("Identification");
        idTextField.setBorder(null);
        idTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        idTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTextFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        signUpPanel.add(idTextField, gridBagConstraints);

        passwordField.setBackground(new java.awt.Color(143, 182, 208));
        passwordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("             ");
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passwordField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        signUpPanel.add(passwordField, gridBagConstraints);

        add(signUpPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnPanelMouseEntered
        signUpBtnPanel.setBackground(new Color(44, 62, 75));
    }//GEN-LAST:event_signUpBtnPanelMouseEntered

    private void signUpBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnPanelMouseExited
        signUpBtnPanel.setBackground(new Color(143, 182, 208));
    }//GEN-LAST:event_signUpBtnPanelMouseExited

    private void nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextFieldMouseClicked
        if ("Identification".equals(idTextField.getText())) {
            nameTextField.setText("");
            idTextField.setText("");
            passwordField.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_nameTextFieldMouseClicked

    private void idTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTextFieldMouseClicked
        if ("Identification".equals(idTextField.getText())) {
            nameTextField.setText("");
            idTextField.setText("");
            passwordField.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_idTextFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if ("Identification".equals(idTextField.getText())) {
            nameTextField.setText("");
            idTextField.setText("");
            passwordField.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void signUpBtnPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnPanelMouseReleased
        try {
            if (controller.signUp()) {
                controller.getView().MessageLabel.setText("You have successfully registered");
                controller.getView().MessageLabel.setForeground(new Color(102, 255, 102));
                controller.getView().MessageLabel.setVisible(true);
                controller.changePanel(controller.getSignIn());
            } else {
                controller.getView().MessageLabel.setText("Please fill all the blanks");
                controller.getView().MessageLabel.setForeground(new Color(255,204,51));
                controller.getView().MessageLabel.setVisible(true);
            }
        } catch (Exception ex) {
            controller.getView().MessageLabel.setText("Error: This user already exists");
            controller.getView().MessageLabel.setForeground(new Color(253, 0, 101));
            controller.getView().MessageLabel.setVisible(true);
        }
    }//GEN-LAST:event_signUpBtnPanelMouseReleased

    @Override
    public void update(Observable o, Object arg) {
        validate();
        repaint();
    }

    private LoginController controller;
    private LoginModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler downfiller;
    private javax.swing.Box.Filler iconfiller;
    private javax.swing.JLabel idIconLabel;
    public javax.swing.JTextField idTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.Box.Filler leftIconfiller;
    private javax.swing.JLabel nameIconLabel;
    private javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameTextField;
    public javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordIconLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.Box.Filler rightIconfiller;
    private javax.swing.JPanel signUpBtnPanel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel singUpLabel;
    private javax.swing.Box.Filler upfiller;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
