package app.view;

import app.controller.LoginController;
import app.model.LoginModel;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Daniel Sánchez S.
 * @version 2.0
 */
public class SignInView extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form SingInView
     */
    public SignInView() {
        initComponents();
        this.setBackground(new Color(143, 182, 208, 60));
    }

    public void setController(LoginController controller) {
        this.controller = controller;
    }

    public LoginModel getModel() {
        return model;
    }

    public void setModel(LoginModel model) {
        this.model = model;
        model.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        signInPanel = new javax.swing.JPanel();
        userIconLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        idIconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        passwordLabel = new javax.swing.JLabel();
        passwordIconLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        upfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        downfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 32));
        iconfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        leftIconfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        rightIconfiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        passwordField = new javax.swing.JPasswordField();
        signInBtnPanel = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        singUpLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        signInPanel.setBackground(new java.awt.Color(143, 182, 208));
        signInPanel.setPreferredSize(new java.awt.Dimension(325, 400));
        signInPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signInPanelKeyReleased(evt);
            }
        });
        signInPanel.setLayout(new java.awt.GridBagLayout());

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-user-60.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 44);
        signInPanel.add(userIconLabel, gridBagConstraints);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("User:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signInPanel.add(userLabel, gridBagConstraints);

        idTextField.setBackground(new java.awt.Color(143, 182, 208));
        idTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setText("Identification");
        idTextField.setBorder(null);
        idTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        idTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        idTextField.setPreferredSize(new java.awt.Dimension(125, 16));
        idTextField.setSelectedTextColor(new java.awt.Color(252, 252, 252));
        idTextField.setSelectionColor(new java.awt.Color(255, 255, 255));
        idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTextFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.1;
        signInPanel.add(idTextField, gridBagConstraints);

        idIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-user-24.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signInPanel.add(idIconLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setToolTipText("");
        jSeparator1.setMinimumSize(new java.awt.Dimension(15, 5));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(15, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signInPanel.add(jSeparator1, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signInPanel.add(passwordLabel, gridBagConstraints);

        passwordIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app.gui.icons/icons8-privacy-24.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signInPanel.add(passwordIconLabel, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setToolTipText("");
        jSeparator2.setMinimumSize(new java.awt.Dimension(15, 5));
        jSeparator2.setOpaque(true);
        jSeparator2.setPreferredSize(new java.awt.Dimension(15, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        signInPanel.add(jSeparator2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        signInPanel.add(upfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        signInPanel.add(downfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        signInPanel.add(iconfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        signInPanel.add(leftIconfiller, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        signInPanel.add(rightIconfiller, gridBagConstraints);

        passwordField.setBackground(new java.awt.Color(143, 182, 208));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("Password123");
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passwordField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordField.setPreferredSize(new java.awt.Dimension(125, 16));
        passwordField.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        passwordField.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.1;
        signInPanel.add(passwordField, gridBagConstraints);

        signInBtnPanel.setBackground(new java.awt.Color(143, 182, 208));
        signInBtnPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        signInBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInBtnPanel.setPreferredSize(new java.awt.Dimension(72, 32));
        signInBtnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInBtnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInBtnPanelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInBtnPanelMouseReleased(evt);
            }
        });
        signInBtnPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signInBtnPanelKeyReleased(evt);
            }
        });

        signInLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setText("Sign In");
        signInBtnPanel.add(signInLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        signInPanel.add(signInBtnPanel, gridBagConstraints);

        signUpPanel.setBackground(new java.awt.Color(143, 182, 208));
        signUpPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        signUpPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpPanel.setPreferredSize(new java.awt.Dimension(72, 32));
        signUpPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpPanelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signUpPanelMouseReleased(evt);
            }
        });

        singUpLabel.setBackground(new java.awt.Color(255, 255, 255));
        singUpLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        singUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        singUpLabel.setText("Sign Up");
        signUpPanel.add(singUpLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        signInPanel.add(signUpPanel, gridBagConstraints);

        add(signInPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTextFieldMouseClicked
        if ("Identification".equals(idTextField.getText())) {
            idTextField.setText("");
            passwordField.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_idTextFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if ("Identification".equals(idTextField.getText())) {
            idTextField.setText("");
            passwordField.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void signInBtnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnPanelMouseEntered
        signInBtnPanel.setBackground(new Color(44, 62, 75));
    }//GEN-LAST:event_signInBtnPanelMouseEntered

    private void signInBtnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnPanelMouseExited
        signInBtnPanel.setBackground(new Color(143, 182, 208));
    }//GEN-LAST:event_signInBtnPanelMouseExited

    private void signUpPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpPanelMouseEntered
        signUpPanel.setBackground(new Color(44, 62, 75));
    }//GEN-LAST:event_signUpPanelMouseEntered

    private void signUpPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpPanelMouseExited
        signUpPanel.setBackground(new Color(143, 182, 208));
    }//GEN-LAST:event_signUpPanelMouseExited

    private void signUpPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpPanelMouseReleased
        controller.changePanel(controller.getSignUp());
    }//GEN-LAST:event_signUpPanelMouseReleased

    private void signInBtnPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnPanelMouseReleased
        signIn();
    }//GEN-LAST:event_signInBtnPanelMouseReleased

    private void signInBtnPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signInBtnPanelKeyReleased
        signInLabel.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    signIn();
                }
            }
        });
    }//GEN-LAST:event_signInBtnPanelKeyReleased

    private void signInPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signInPanelKeyReleased
        signInLabel.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    signIn();
                }
            }
        });
    }//GEN-LAST:event_signInPanelKeyReleased

    private void signIn() {
        try {
            controller.initiatePrincipal(controller.login());
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            controller.getView().MessageLabel.setText("Error: Incorrect data");
            controller.getView().MessageLabel.setForeground(new Color(253, 0, 101));
            controller.getView().MessageLabel.setVisible(true);
        }
    }

    @Override
    public void update(Observable o, Object arg) {
        validate();
        repaint();
    }

    private LoginController controller;
    private LoginModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler downfiller;
    private javax.swing.Box.Filler iconfiller;
    private javax.swing.JLabel idIconLabel;
    public javax.swing.JTextField idTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.Box.Filler leftIconfiller;
    public javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordIconLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.Box.Filler rightIconfiller;
    private javax.swing.JPanel signInBtnPanel;
    private javax.swing.JLabel signInLabel;
    public javax.swing.JPanel signInPanel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel singUpLabel;
    private javax.swing.Box.Filler upfiller;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
